events {
    worker_connections 1024;
}

http {
    server_names_hash_bucket_size 64;

    # HTTP (80) -> HTTPS (443) Redirect
    server {
        listen 80 default_server;
        server_name certusdiagnostics.in www.certusdiagnostics.in admin.certusdiagnostics.in _;

        return 301 https://$host$request_uri;
    }

    # Admin App Routing (HTTPS)
    server {
        listen 443 ssl;
        server_name admin.certusdiagnostics.in;

        ssl_certificate /etc/letsencrypt/live/certusdiagnostics.in/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/certusdiagnostics.in/privkey.pem;

        location /api/v1/ {
            proxy_pass http://backend:8080/api/v1/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        location /uploads/ {
            proxy_pass http://backend:8080/uploads/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        location / {
            proxy_pass http://admin:80;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }

    # Client App Routing (HTTPS)
    server {
        listen 443 ssl default_server;
        server_name certusdiagnostics.in www.certusdiagnostics.in _;

        ssl_certificate /etc/letsencrypt/live/certusdiagnostics.in/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/certusdiagnostics.in/privkey.pem;

        location /api/v1/ {
            proxy_pass http://backend:8080/api/v1/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        location /uploads/ {
            proxy_pass http://backend:8080/uploads/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        location / {
            proxy_pass http://client:80;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}
