package com.rehnoor.certusbackend.controller.admin;

import com.rehnoor.certusbackend.dto.CategoryOrderDTO;
import com.rehnoor.certusbackend.dto.PackageCategoryRequestDTO;
import com.rehnoor.certusbackend.dto.PackageCategoryResponse;
import com.rehnoor.certusbackend.model.PackageCategory;
import com.rehnoor.certusbackend.repository.PackageCategoryRepository;
import com.rehnoor.certusbackend.service.PackageCategoryService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.security.access.prepost.PreAuthorize;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.multipart.MultipartFile;

import javax.print.attribute.standard.Media;
import java.io.IOException;
import java.util.List;
import java.util.Map;

@PreAuthorize("hasRole('ADMIN')")
@RestController
@RequestMapping("/api/v1/admin/package-categories")
public class PackageCategoryAdminController {
    @Autowired
    PackageCategoryService packageCategoryService;

    @Autowired
    PackageCategoryRepository packageCategoryRepository;

    @GetMapping("")
    public ResponseEntity<?> getAllPackageCategories() {
        // first we need to sort by date, then by status available true's should come first,
        // the frontend can slightly gray it out

        List<PackageCategoryResponse> result = packageCategoryService.getAllPackageCategories();
        return ResponseEntity.ok(Map.of("success", true, "data", result));
    }

    @PostMapping(value = "", consumes = MediaType.MULTIPART_FORM_DATA_VALUE)
    public ResponseEntity<?> uploadPackageCategory(@ModelAttribute PackageCategoryRequestDTO payload, @RequestParam(value="image", required = false) MultipartFile image) throws IOException {

        // if the display order is not given, we want it autogenerated
        packageCategoryService.uploadPackageCategory(payload.getName(), image);
        return ResponseEntity.ok(Map.of("success", true, "message", "Category Saved Successfully!"));

    }

    @PatchMapping(value = "/{categoryId}", consumes = MediaType.MULTIPART_FORM_DATA_VALUE)
    public ResponseEntity<?> updatePackageCategory(@PathVariable Long categoryId, @ModelAttribute PackageCategoryRequestDTO payload, @RequestParam(value="image", required = false) MultipartFile image) throws IOException {
        // admin wants to update the name, imageUrl, status or display order of the
        packageCategoryService.updatePackageCategory(categoryId, payload, image);
        return ResponseEntity.ok(
                Map.of(
                        "success", true,
                        "message", "Category Updated Successfully!"
                )
        );

    }

    // SOFT DELETE
    @DeleteMapping("/{categoryId}")
    public ResponseEntity<?> deletePackageCategory(@PathVariable Long categoryId) {
        packageCategoryService.deletePackageCategory(categoryId);
        return ResponseEntity.ok(Map.of("success", true, "message", "Category deleted Successfully!"));
    }


    @PutMapping("/reorder")
    public ResponseEntity<?> reorderCategories(@RequestBody List<CategoryOrderDTO> orderList) {
        if(packageCategoryService.reorder(orderList))
        {
            return ResponseEntity.ok(Map.of("success", true, "message", "Order Changed Successfully"));
        }
        else{
            return ResponseEntity.badRequest().build();
        }
    }
}
